---
title: Isaccavalcante.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Isac Cavalcante
description: Just a tech
avatar: https://avatars3.githubusercontent.com/u/13874084?v=4&s=460
footer-links:
  dribbble: 
  email: isaccavalcante@alu.ufc.br
  facebook: 
  flickr: 
  github: isaccavalcante
  instagram: isac.jpg
  linkedin: isaccavalcante
  pinterest: 
  rss: 
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
url: 
baseurl: ''
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
- jemoji
- jekyll-theme-hacker
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
theme: jekyll-theme-midnight
